name: re_highlight
description: Re-Highlight is a powerful text syntax highlighting library.
version: 0.0.4
homepage: https://reqable.com
repository: https://github.com/reqable/re-highlight

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
